apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx # Use the same template > metadata > labels > app value from the deployment.yaml file
  ports:
    - protocol: TCP
      port: 80